COMPONENT=WSNBlockchainPPC
SENSORBOARD=mda100
CFLAGS+=-I../
CFLAGS+=-I$(TINYOS_ROOT_DIR)/tos/lib/printf
CFLAGS+=-I$(TINYOS_ROOT_DIR)/tos/sensorboards/mda100
include $(TINYOS_ROOT_DIR)/Makefile.include

